version: '3'

volumes:
  db:
  redis:
  cert_cache:
  soundboard:

networks:
  default:

services:
  app:
    build:
      # We change context so that we can copy the local repo in during
      # development
      context: ../
      dockerfile: yagpdb_docker/Dockerfile
    restart: always
    command:
      # - "/app/yagpdb"
      - "-all"
      - "-pa"
      - "-exthttps=true"
      - "-https=false"
    depends_on:
      - redis
      - db
    networks:
      - default
    volumes:
      - cert_cache:/app/cert
      - soundboard:/app/soundboard
    ports:
      - '8081:80'
      - '4431:443'
    env_file:
      - app.env

 redis:
    image: redis
    restart: always
    networks:
      - default
    volumes:
      - redis:/data

  db:
    image: postgres:11
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - db.env
